# Setup: Generate Sample Dataset

This cell creates the required folder structure (`data/raw/` and `data/processed/`) relative to the notebook, and generates the sample CSV dataset with missing values. 
This ensures the dataset is ready for cleaning functions and saves it to `data/raw/sample_data.csv`.

In [1]:
# --- packages this notebook needs (uncomment and run once, then re-comment) ---
# !pip install numpy
# !pip install pandas

In [2]:
# --- files this notebook needs (run me first - I only report, I change nothing) ---
from pathlib import Path
import sys

HOMEWORK_DIR = Path.cwd()
ROOT = HOMEWORK_DIR

DATA_RAW = ROOT / "data" / "raw"
DATA_PROCESSED = ROOT / "data" / "processed"
SRC_DIR = ROOT / "src"

DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print("Homework directory:", HOMEWORK_DIR)
print("Raw data directory:", DATA_RAW)
print("Processed data directory:", DATA_PROCESSED)
print("Source directory:", SRC_DIR)

CHECKS = [
    ("src/cleaning.py", "NEEDED", "YOU write this in the homework - the import fails until you do"),
]

print(f"Looking in: {ROOT}\n")
missing = 0
for rel, kind, note in CHECKS:
    here = (ROOT / rel).exists()
    if not here and kind == "NEEDED":
        missing += 1
    print(f"  [{'OK ' if here else 'MISS'}]  {kind:<8}  {rel:<34}  {note}")

if missing:
    print(f"\n{missing} needed file(s) missing. Put them at the paths above, relative to:\n  {ROOT}")
    print("If that folder looks wrong, you are running the notebook from the wrong place.")
else:
    print("\nAll needed files present.")

Homework directory: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6
Raw data directory: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6/data/raw
Processed data directory: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6/data/processed
Source directory: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6/src
Looking in: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6

  [OK ]  NEEDED    src/cleaning.py                     YOU write this in the homework - the import fails until you do

All needed files present.

In [3]:
import os
import pandas as pd
import numpy as np

# Define folder paths relative to this notebook
raw_dir = DATA_RAW
processed_dir = DATA_PROCESSED

# Create folders if they don't exist
os.makedirs(raw_dir, exist_ok=True)
os.makedirs(processed_dir, exist_ok=True)

# Define the sample data
data = {
    'age': [34, 45, 29, 50, 38, np.nan, 41],
    'income': [55000, np.nan, 42000, 58000, np.nan, np.nan, 49000],
    'score': [0.82, 0.91, np.nan, 0.76, 0.88, 0.65, 0.79],
    'zipcode': ['90210', '10001', '60614', '94103', '73301', '12345', '94105'],
    'city': ['Beverly', 'New York', 'Chicago', 'SF', 'Austin', 'Unknown', 'San Francisco'],
    'extra_data': [np.nan, 42, np.nan, np.nan, np.nan, 5, np.nan]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV in raw data folder
csv_path = raw_dir / "sample_data.csv"
if not os.path.exists(csv_path):
    df.to_csv(csv_path, index=False)
    print(f'Sample dataset created and saved to {csv_path}')
else:
    print(f'File already exists at {csv_path}. Skipping CSV creation to avoid overwrite.')

File already exists at /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6/data/raw/sample_data.csv. Skipping CSV creation to avoid overwrite.

# Homework Starter — Stage 6: Data Preprocessing
Use this notebook to apply your cleaning functions and save processed data.

In [4]:
import pandas as pd

# Uncomment once you have written src/cleaning.py (see the homework sheet).
# Until then this import fails - the module is yours to create.
from src import cleaning

## Load Raw Dataset

In [5]:
df = pd.read_csv(raw_dir / "sample_data.csv")
df.head()

    age   income  score  zipcode      city  extra_data
0  34.0  55000.0   0.82    90210   Beverly         NaN
1  45.0      NaN   0.91    10001  New York        42.0
2  29.0  42000.0    NaN    60614   Chicago         NaN
3  50.0  58000.0   0.76    94103        SF         NaN
4  38.0      NaN   0.88    73301    Austin         NaN

## Apply Cleaning Functions

In [6]:
# Apply cleaning functions

# 1. Drop columns with more than 50% missing values
df_cleaned = cleaning.drop_missing(df, threshold=0.5)

# 2. Fill missing numeric values with the median
df_cleaned = cleaning.fill_missing_median(
    df_cleaned,
    ['age', 'income', 'score']
)

# 3. Normalize selected numeric columns
df_cleaned = cleaning.normalize_data(
    df_cleaned,
    ['age', 'income', 'score']
)

df_cleaned

        age  income     score  zipcode           city
0  0.238095  0.8125  0.653846    90210        Beverly
1  0.761905  0.6250  1.000000    10001       New York
2  0.000000  0.0000  0.596154    60614        Chicago
3  1.000000  1.0000  0.423077    94103             SF
4  0.428571  0.6250  0.884615    73301         Austin
5  0.500000  0.6250  0.000000    12345        Unknown
6  0.571429  0.4375  0.538462    94105  San Francisco

## Save Cleaned Dataset

In [7]:
# df.to_csv('data/processed/sample_data_cleaned.csv', index=False)
processed_path = DATA_PROCESSED / "cleaned_data.csv"

df_cleaned.to_csv(processed_path, index=False)

print("Cleaned dataset saved to:", processed_path)

Cleaned dataset saved to: /Users/juan/Desktop/nyu bootcamp/bootcamp_henry_dong/homework/homework6/data/processed/cleaned_data.csv

## Compare Original and Cleaned Data

In [8]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_cleaned.shape)

print("\nOriginal missing values:")
print(df.isna().sum())

print("\nCleaned missing values:")
print(df_cleaned.isna().sum())

print("\nOriginal data:")
display(df)

print("\nCleaned data:")
display(df_cleaned)

Original shape: (7, 6)
Cleaned shape: (7, 5)

Original missing values:
age           1
income        3
score         1
zipcode       0
city          0
extra_data    5
dtype: int64

Cleaned missing values:
age        0
income     0
score      0
zipcode    0
city       0
dtype: int64

Original data:

    age   income  score  zipcode           city  extra_data
0  34.0  55000.0   0.82    90210        Beverly         NaN
1  45.0      NaN   0.91    10001       New York        42.0
2  29.0  42000.0    NaN    60614        Chicago         NaN
3  50.0  58000.0   0.76    94103             SF         NaN
4  38.0      NaN   0.88    73301         Austin         NaN
5   NaN      NaN   0.65    12345        Unknown         5.0
6  41.0  49000.0   0.79    94105  San Francisco         NaN

Cleaned data:

        age  income     score  zipcode           city
0  0.238095  0.8125  0.653846    90210        Beverly
1  0.761905  0.6250  1.000000    10001       New York
2  0.000000  0.0000  0.596154    60614        Chicago
3  1.000000  1.0000  0.423077    94103             SF
4  0.428571  0.6250  0.884615    73301         Austin
5  0.500000  0.6250  0.000000    12345        Unknown
6  0.571429  0.4375  0.538462    94105  San Francisco

## Cleaning Strategy and Assumptions

The preprocessing workflow uses three main steps:

1. Columns with more than 50% missing values are removed because they contain too little reliable information. In this dataset, `extra_data` is removed for this reason.

2. Missing values in the numeric columns `age`, `income`, and `score` are filled using the median. Median imputation is used because it is less sensitive to extreme values than the mean.

3. The numeric columns `age`, `income`, and `score` are normalized using Min-Max scaling so that their values fall between 0 and 1.

The `zipcode` and `city` columns are kept unchanged because they are identifier/categorical fields and should not be normalized.

This cleaning strategy assumes that the missing numeric values can reasonably be represented by the median of the observed values and that removing a column with more than 50% missing data is preferable to imputing most of its values.